version: '3.8'

services:
  server:
    container_name: server
    restart: unless-stopped
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    env_file:
      - ./server/.env
    volumes:
      - ./server/src:/app/src
    networks:
      - devat

  client:
    container_name: client
    restart: unless-stopped
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/src
    depends_on:
      - server
    networks:
      - devat

networks:
  devat:
